In [2]:
# Install hydesign if needed
try:
    import hydesign
except ModuleNotFoundError:
    !pip install git+https://gitlab.windenergy.dtu.dk/TOPFARM/hydesign.git
    
import os
import time
import yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from hydesign.examples import examples_filepath

In [4]:
pr_df = pd.read_csv(f'{examples_filepath}example_sites_data_extraction/2030-EL_PRICE_raw.csv', parse_dates=True)
pr_df['Time'] = pd.DatetimeIndex(pr_df['Time'].apply(lambda x: x.replace('2030','2012')))
pr_df = pr_df.set_index('Time')

# Replace weather year index from 2030 to 2012
pr_df = pr_df.reindex(pd.date_range('2012-01-01 00:00','2012-12-31 23:00', freq='1h'),fill_value=np.NaN)

In [5]:
# Fill in missing dates with previous date
for t in list(pd.date_range('2012-02-29 00:00','2012-02-29 23:00', freq='1h')) + list(pd.date_range('2012-12-31 00:00','2012-12-31 23:00', freq='1h')):
    pr_df.loc[t,:] =  pr_df.loc[pd.to_datetime(t-pd.Timedelta('1d')),:]
    
pr_df.to_csv(f'{examples_filepath}Europe/2030-EL_PRICE.csv')

In [6]:
pr_df

,PL_R,BE_R,DE_CS,DE_ME,DE_NE,DE_NW,DK_W,DK_E,EE_R,FI_R,...,NL_R,NO_M,NO_MW,NO_N,NO_SE,NO_SW,SE_M,SE_N1,SE_N2,SE_S
2012-01-01 00:00:00,9.275280,4.867785,4.868785,4.867785,4.866785,4.867785,4.867785,8.343220,9.276280,9.275280,...,4.867785,4.870785,4.869785,4.869785,4.870785,4.868785,9.274280,9.274280,9.273280,8.344220
2012-01-01 01:00:00,8.344220,4.867785,4.866785,4.865785,4.864785,4.867785,4.867785,8.343220,8.348220,8.347220,...,4.867785,4.870785,4.869785,4.869785,4.870785,4.868785,8.346220,8.346220,8.345220,8.344220
2012-01-01 02:00:00,8.343220,4.867785,4.866785,4.865785,4.864785,4.867785,4.867785,8.342220,9.113772,9.114772,...,4.867785,4.870785,4.869785,4.869785,4.870785,4.868785,9.113772,9.113772,9.112772,8.344220
2012-01-01 03:00:00,4.867785,4.867785,4.866785,4.865785,4.864785,4.867785,4.867785,4.868785,9.113772,9.114772,...,4.867785,4.870785,4.869785,4.871785,4.870785,4.868785,9.113772,9.113772,9.112772,4.869785
2012-01-01 04:00:00,4.867785,4.867785,4.867785,4.866785,3.512090,4.867785,4.867785,4.868785,9.274280,9.275280,...,4.867785,4.870785,4.869785,4.871785,4.870785,4.868785,9.274280,9.274280,9.273280,4.869785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-12-31 19:00:00,8.344220,4.869785,4.868785,4.867785,4.866785,4.867785,4.867785,4.868785,13.692120,13.691120,...,4.869785,4.870785,4.869785,4.871785,4.870785,4.868785,13.690120,13.690120,13.689120,8.344220
2012-12-31 20:00:00,8.344220,4.868785,4.868785,4.867785,4.866785,4.867785,4.867785,4.868785,11.974622,11.973622,...,4.869785,4.870785,4.869785,4.869785,4.870785,4.868785,11.972622,11.972622,11.971622,8.344220
2012-12-31 21:00:00,8.344220,4.869785,4.868785,4.867785,4.866785,4.867785,4.867785,4.868785,11.507224,11.506224,...,4.868785,4.870785,4.869785,4.869785,4.870785,4.868785,11.505224,11.505224,11.504224,8.344220
2012-12-31 22:00:00,4.868785,4.867785,4.867785,4.866785,4.864785,4.866785,4.866785,4.867785,9.274280,9.275280,...,4.867785,4.869785,4.868785,4.870785,4.869785,4.867785,9.274280,9.274280,9.273280,4.868785
2012-12-31 23:00:00,4.867785,4.867785,4.866785,4.865785,4.864785,4.865785,4.866785,4.866785,9.113772,9.114772,...,4.867785,4.869785,4.868785,4.870785,4.869785,4.867785,4.870785,4.872785,4.871785,4.867785